---
# tasks file for nightscout-app-setup
- name: Run preconfig tasks
  ansible.builtin.include_tasks: preconfig.yml
- name: Run install tasks
  ansible.builtin.include_tasks: install.yml
- name: Run postinstall tasks
  ansible.builtin.include_tasks: postinstall.yml
