---
- name: Update all packages
  ansible.builtin.yum:
    name: '*'
    state: latest
    update_only: true

- name: Ensure a list of yum packages are installed
  ansible.builtin.yum:
    name: "{{ packages }}"
    state: present
    update_cache: true
  vars:
    packages:
      - python-pip
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
      - amazon-linux-extras

- name: Add extras repository
  ansible.builtin.shell: yum-config-manager --enable extras

- name: Install docker-ce (centos) via amazon-linux-extras packages
  ansible.builtin.shell: "amazon-linux-extras install docker -y"

- name: Enable Docker CE service at startup
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Ensure Python pip packages are installed
  ansible.builtin.pip:
    name: "{{ packages }}"
  vars:
    packages:
      - boto
      - boto3
      - docker-compose
